$primary_paletteKeyColor = ffffff
$secondary_paletteKeyColor = 00ffaa
$tertiary_paletteKeyColor = aaff00
$neutral_paletteKeyColor = 808080
$neutral_variant_paletteKeyColor = 808080
$background = 000000
$onBackground = ffffff
$surface = 000000
$surfaceDim = 000000
$surfaceBright = 242424
$surfaceContainerLowest = 0a0a0a
$surfaceContainerLow = 101010
$surfaceContainer = 101010
$surfaceContainerHigh = 151515
$surfaceContainerHighest = 1c1c1c
$onSurface = ffffff
$surfaceVariant = 1c1c1c
$onSurfaceVariant = cccccc
$inverseSurface = ffffff
$inverseOnSurface = 000000
$outline = 3a3a3a
$outlineVariant = 1f1f1f
$shadow = 000000
$scrim = 000000
$surfaceTint = ffffff
$primary = ffffff
$onPrimary = 000000
$primaryContainer = 151515
$onPrimaryContainer = ffffff
$inversePrimary = 00ffaa
$secondary = 00ffaa
$onSecondary = 000000
$secondaryContainer = 151515
$onSecondaryContainer = 00ffaa
$tertiary = aaff00
$onTertiary = 000000
$tertiaryContainer = 151515
$onTertiaryContainer = aaff00
$error = ff2e88
$onError = 000000
$errorContainer = 3a0014
$onErrorContainer = ffb3cf
$primaryFixed = ffffff
$primaryFixedDim = cccccc
$onPrimaryFixed = 000000
$onPrimaryFixedVariant = 666666
$secondaryFixed = 00ffaa
$secondaryFixedDim = 00cc88
$onSecondaryFixed = 000000
$onSecondaryFixedVariant = 003d2a
$tertiaryFixed = aaff00
$tertiaryFixedDim = 88cc00
$onTertiaryFixed = 000000
$onTertiaryFixedVariant = 2a3d00
$term0 = 000000
$term1 = ff2e88
$term2 = 00ffaa
$term3 = aaff00
$term4 = 0000ff
$term5 = ffffff
$term6 = 00ffaa
$term7 = cccccc
$term8 = 666666
$term9 = ff2e88
$term10 = 00ffaa
$term11 = aaff00
$term12 = 0000ff
$term13 = ffffff
$term14 = 00ffaa
$term15 = ffffff
$rosewater = ffffff
$flamingo = ffffff
$pink = ffffff
$mauve = ffffff
$red = ff2e88
$maroon = ff2e88
$peach = aaff00
$yellow = aaff00
$green = 00ffaa
$teal = 00ffaa
$sky = 0000ff
$sapphire = 0000ff
$blue = 0000ff
$lavender = ffffff
$klink = 00ffaa
$klinkSelection = aaff00
$kvisited = 0000ff
$kvisitedSelection = ffffff
$knegative = ff2e88
$knegativeSelection = ff2e88
$kneutral = aaff00
$kneutralSelection = aaff00
$kpositive = 00ffaa
$kpositiveSelection = 00ffaa
$text = ffffff
$subtext1 = cccccc
$subtext0 = 999999
$overlay2 = 666666
$overlay1 = 555555
$overlay0 = 3d3d3d
$surface2 = 1c1c1c
$surface1 = 151515
$surface0 = 101010
$base = 000000
$mantle = 0a0a0a
$crust = 101010
$success = 00ffaa
$onSuccess = 000000
$successContainer = 151515
$onSuccessContainer = 00ffaa
